export const TODO_CREATE_REQUESTED = 'TODO_CREATE_REQUESTED'
export const TODO_CREATE_SUCCEEDED = 'TODO_CREATE_SUCCEEDED'
export const TODO_CREATE_FAILED = 'TODO_CREATE_FAILED'

export const TODOS_GET_REQUESTED = 'TODOS_GET_REQUESTED'
export const TODOS_GET_SUCCEEDED = 'TODOS_GET_SUCCEEDED'
export const TODOS_GET_FAILED = 'TODOS_GETFAILED'
